# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Publish Unit Test Results
      if: ${{ success() || failure() }}
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      with:
        check_name: Unit Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: ./**/pytest-result.xml
    - name: Extract coverage
      id: extract_coverage
      if: ${{ success() || failure() }}
      uses: brunotoshio/python-coverage-action@v0.3.0
      with:
        filepath: coverage.json
    - name: Publish coverage
      uses: mshick/add-pr-comment@v1
      with:
        message: ${{ steps.extract_coverage.outputs.result }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
